### PR TITLE
add rotation element

### PR DESCRIPTION
**Pull request by dericed**
to address https://github.com/Matroska-Org/matroska-specification/issues/269

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
integer and in radians?
how do you indicate e.g. π radians (value for 180° rotation) with an integer?

**Comment by dericed** [comment]
@JeromeMartinez rotate = `180*(PI/180)` .... ok i see your point. Prefer in degrees?

**Comment by JeromeMartinez** [comment]
I usually prefer SI units (so radians with floating point number?) but it makes the most classic values (π, π/2, -π/2) approximations (IEEE representation of π is not exact).
From the issue ticket using the matrix values as in MP4 is not appreciated.
So maybe degrees is the "less worse" solution, -90/0/90/180 being the most used values.
I imagine to prefer a floating number in case of weird need of e.g. 0.1°, but maybe too much (and 4 bytes used instead of 1 or 2 bytes.
Do others have better idea?

**Comment by dericed** [comment]
closing as discussed in https://github.com/Matroska-Org/matroska-specification/issues/269#issuecomment-426390778

**Comment by robUx4** [comment]
Technically for 360 videos there are 3 degrees of movement and so 3 different values.

This one is the rotation on the Z axis (flat videos being X,Y).

**Pull request closed without merging**
