### PR TITLE
Timecode timestamp

### PR DESCRIPTION
**Pull request by robUx4**
As seen on #197

### CODE REVIEW

**Comment by hubblec4** [comment]
What is the state?
Mosu has adjusted the "stamp" word in the MTX-exe's.
Could we change it here also now?

**Comment by mbunkus** [comment]
I'm OK with renaming now. @robUx4 please resolve the conflicts, force-push and then we can merge.

**Comment by ablwr** [comment]
Status of this still for @robUx4 to resolve conflicts, re-review and intend to merge?

**Comment by robUx4** [comment]
On it.

**Comment by robUx4** [comment]
Feel free to merge.

**Comment by robUx4** [comment]
Still good with merging this @mbunkus ?

**Comment by mbunkus** [comment]
Yeah I'm fine with it.

**Pull request merged**
