### PR TITLE
add vocabulary restrictions table

### PR DESCRIPTION
**Pull request by dericed**
also thx to @kieranjol

### CODE REVIEW

**Comment by kieranjol** [comment]
I'm seeing some overflows of elements in tables that contain more than two rows. (xml and txt here just for reference: https://gist.github.com/kieranjol/a027b009296450f4f504d7ee845b3101)

For example, FieldOrder renders like this in txt:
```
   +---------------------------------+-----------------+---------------+
   | value                           | label           | documentation |
   +---------------------------------+-----------------+---------------+
   | "0"                             | progressive     | "1"           |
   | tff                             | Top field       | "2"           |
   |                                 | displayed       |               |
   |                                 | first. Top      |               |
   |                                 | field stored    |               |
   |                                 | first.          |               |
   | undetermined                    | "6"             | bff           |
   | Bottom field displayed first.   | "9"             | bff(swapped)  |
   | Bottom field stored first.      |                 |               |
   | Top field displayed first.      | "14"            | tff(swapped)  |
   | Fields are interleaved in       |                 |               |
   | storage with the top line of    |                 |               |
   | the top field stored first.     |                 |               |
   | Bottom field displayed first.   |
   | Fields are interleaved in       |
   | storage with the top line of    |
   | the top field stored first.     |
   +---------------------------------+-----------------+---------------+

and I see similar issues with HTML.
```
$ mmark -version
1.3.6
kieranjol@kieranjol-ThinkPad-T420:~/matroska-specification$ xml2rfc --version
2.5.1
kieranjol@kieranjol-ThinkPad-T420:~/matroska-specification$ xsltproc -version
Using libxml 20903, libxslt 10128 and libexslt 817
xsltproc was compiled against libxml 20903, libxslt 10128 and libexslt 817
libxslt 10128 was compiled against libxml 20903
libexslt 817 was compiled against libxml 20903

```


Command line output:
```
:~/matroska-specification$ make clean
RFC rendering has been tested with mmark version 1.3.4 and xml2rfc 2.5.1, please ensure these are installed and recent enough.
rm -f -f draft-ietf-cellar-matroska-00.txt draft-ietf-cellar-matroska-00.html draft-ietf-cellar-matroska-00.md draft-ietf-cellar-matroska-00.xml ebml_matroska_elements.md ebml_matroska_elements4rfc.md matroska_tagging_registry.md
rm -f -f draft-ietf-cellar-codecs-00.txt draft-ietf-cellar-codecs-00.html draft-ietf-cellar-codecs-00.md draft-ietf-cellar-codecs-00.xml
rm -f -f draft-ietf-cellar-tags-00.txt draft-ietf-cellar-tags-00.html draft-ietf-cellar-tags-00.md draft-ietf-cellar-tags-00.xml
rm -f -rf _site
kieranjol@kieranjol-ThinkPad-T420:~/matroska-specification$ make
RFC rendering has been tested with mmark version 1.3.4 and xml2rfc 2.5.1, please ensure these are installed and recent enough.
xsltproc transforms/ebml_schema2markdown4rfc.xsl ebml_matroska.xml > ebml_matroska_elements4rfc.md
cat index_matroska.md diagram.md matroska_schema_section_header.md ebml_matroska_elements4rfc.md ordering.md chapters.md attachments.md cues.md streaming.md menu.md notes.md | grep -v '^---' > draft-ietf-cellar-matroska-00.md
mmark -xml2 -page draft-ietf-cellar-matroska-00.md > draft-ietf-cellar-matroska-00.xml
2018/07/25 19:23:23 mmark: syntax not supported: TableCell: colspan=2
2018/07/25 19:23:23 mmark: syntax not supported: TableCell: colspan=2
xml2rfc --html draft-ietf-cellar-matroska-00.xml -o draft-ietf-cellar-matroska-00.html
Parsing file draft-ietf-cellar-matroska-00.xml
Created file draft-ietf-cellar-matroska-00.html
xml2rfc draft-ietf-cellar-matroska-00.xml -o draft-ietf-cellar-matroska-00.txt
Parsing file draft-ietf-cellar-matroska-00.xml
WARNING: Illegal character replaced in string: &#8776;
WARNING: artwork outdented 1 characters to avoid overrunning right margin around input line 520)
WARNING: so many <ttcol>s in <texttable> that some words need to be split near line 6301
Created file draft-ietf-cellar-matroska-00.txt
cat index_codec.md codec_specs.md subtitles.md > draft-ietf-cellar-codecs-00.md
mmark -xml2 -page draft-ietf-cellar-codecs-00.md > draft-ietf-cellar-codecs-00.xml
2018/07/25 19:23:26 mmark: syntax not supported: HRule
2018/07/25 19:23:26 mmark: syntax not supported: HRule
2018/07/25 19:23:26 mmark: syntax not supported: HRule
2018/07/25 19:23:26 mmark: syntax not supported: HRule
2018/07/25 19:23:26 mmark: syntax not supported: HRule
2018/07/25 19:23:26 mmark: syntax not supported: HRule
2018/07/25 19:23:26 mmark: syntax not supported: RawHtmlTag: <CODE BEGINS>
2018/07/25 19:23:26 mmark: syntax not supported: RawHtmlTag: <CODE ENDS>
xml2rfc --html draft-ietf-cellar-codecs-00.xml -o draft-ietf-cellar-codecs-00.html
Parsing file draft-ietf-cellar-codecs-00.xml
Created file draft-ietf-cellar-codecs-00.html
xml2rfc draft-ietf-cellar-codecs-00.xml -o draft-ietf-cellar-codecs-00.txt
Parsing file draft-ietf-cellar-codecs-00.xml
WARNING: artwork outdented 3 characters to avoid overrunning right margin around input line 957)
WARNING: artwork outdented 3 characters to avoid overrunning right margin around input line 1038)
WARNING: artwork outdented 3 characters to avoid overrunning right margin around input line 1108)
WARNING: Output line (from source around line 1108) is 196 characters; longer than 72.  Excess characters: 'ryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding':
  'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, TertiaryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding'

WARNING: Output line (from source around line 1109) is 87 characters; longer than 72.  Excess characters: ',2,2,5,5,30,0,0':
  'Style: Wolf main,Wolf_Rain,56,15724527,15724527,15724527,4144959,0,0,1,1,2,2,5,5,30,0,0'

WARNING: artwork outdented 3 characters to avoid overrunning right margin around input line 1115)
WARNING: Output line (from source around line 1115) is 80 characters; longer than 72.  Excess characters: 'ct, Text':
  'Format: Marked, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'

WARNING: Output line (from source around line 1116) is 115 characters; longer than 72.  Excess characters: 'Et les enregistrements de ses ondes delta ?':
  'Dialogue: Marked=0,0:02:40.65,0:02:41.79,Wolf main,Cher,0000,0000,0000,,Et les enregistrements de ses ondes delta ?'

WARNING: Output line (from source around line 1117) is 87 characters; longer than 72.  Excess characters: ',Toujours rien.':
  'Dialogue: Marked=0,0:02:42.42,0:02:44.15,Wolf main,autre,0000,0000,0000,,Toujours rien.'

WARNING: artwork outdented 3 characters to avoid overrunning right margin around input line 1132)
WARNING: Output line (from source around line 1147) is 76 characters; longer than 72.  Excess characters: '.wav':
  'Wav: 0, 128697,D:\Alex\Anime\- Fansub -\- TAFF -\Wolf's Rain\WR_-_02_Wav.wav'

WARNING: Output line (from source around line 1154) is 196 characters; longer than 72.  Excess characters: 'ryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding':
  'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, TertiaryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding'

WARNING: Output line (from source around line 1155) is 79 characters; longer than 72.  Excess characters: ',30,0,0':
  'Style: Default,Arial,20,65535,65535,65535,-2147483640,-1,0,1,3,0,2,30,30,30,0,0'

WARNING: Output line (from source around line 1156) is 84 characters; longer than 72.  Excess characters: '30,30,30,0,0':
  'Style: Titre_episode,Akbar,140,15724527,65535,65535,986895,-1,0,1,1,0,3,30,30,30,0,0'

WARNING: Output line (from source around line 1157) is 87 characters; longer than 72.  Excess characters: ',2,2,5,5,30,0,0':
  'Style: Wolf main,Wolf_Rain,56,15724527,15724527,15724527,4144959,0,0,1,1,2,2,5,5,30,0,0'

WARNING: Output line (from source around line 1160) is 80 characters; longer than 72.  Excess characters: 'ct, Text':
  'Format: Marked, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'

WARNING: Output line (from source around line 1161) is 115 characters; longer than 72.  Excess characters: 'Et les enregistrements de ses ondes delta ?':
  'Dialogue: Marked=0,0:02:40.65,0:02:41.79,Wolf main,Cher,0000,0000,0000,,Et les enregistrements de ses ondes delta ?'

WARNING: Output line (from source around line 1162) is 87 characters; longer than 72.  Excess characters: ',Toujours rien.':
  'Dialogue: Marked=0,0:02:42.42,0:02:44.15,Wolf main,autre,0000,0000,0000,,Toujours rien.'

WARNING: artwork outdented 3 characters to avoid overrunning right margin around input line 1168)
WARNING: Output line (from source around line 1183) is 76 characters; longer than 72.  Excess characters: '.wav':
  'Wav: 0, 128697,D:\Alex\Anime\- Fansub -\- TAFF -\Wolf's Rain\WR_-_02_Wav.wav'

WARNING: Output line (from source around line 1190) is 196 characters; longer than 72.  Excess characters: 'ryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding':
  'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, TertiaryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding'

WARNING: Output line (from source around line 1191) is 79 characters; longer than 72.  Excess characters: ',30,0,0':
  'Style: Default,Arial,20,65535,65535,65535,-2147483640,-1,0,1,3,0,2,30,30,30,0,0'

WARNING: Output line (from source around line 1192) is 84 characters; longer than 72.  Excess characters: '30,30,30,0,0':
  'Style: Titre_episode,Akbar,140,15724527,65535,65535,986895,-1,0,1,1,0,3,30,30,30,0,0'

WARNING: Output line (from source around line 1193) is 87 characters; longer than 72.  Excess characters: ',2,2,5,5,30,0,0':
  'Style: Wolf main,Wolf_Rain,56,15724527,15724527,15724527,4144959,0,0,1,1,2,2,5,5,30,0,0'

WARNING: artwork outdented 3 characters to avoid overrunning right margin around input line 1202)
WARNING: Output line (from source around line 1202) is 77 characters; longer than 72.  Excess characters: 'lta ?':
  '1,,Wolf main,Cher,0000,0000,0000,,Et les enregistrements de ses ondes delta ?'

WARNING: artwork outdented 3 characters to avoid overrunning right margin around input line 1283)
WARNING: Output line (from source around line 1323) is 76 characters; longer than 72.  Excess characters: 'ngs.':
  'Example entry 3: That stuff to the right of the timestamps are cue settings.'

WARNING: artwork outdented 1 characters to avoid overrunning right margin around input line 1337)
WARNING: artwork outdented 3 characters to avoid overrunning right margin around input line 1406)
WARNING: Output line (from source around line 1406) is 76 characters; longer than 72.  Excess characters: 'ngs.':
  'Example entry 3: That stuff to the right of the timestamps are cue settings.'

Created file draft-ietf-cellar-codecs-00.txt
xsltproc transforms/matroska_tags2markdown4rfc.xsl matroska_tags.xml > matroska_tagging_registry.md
cat index_tags.md tagging.md matroska_tagging_registry.md tagging_end.md > draft-ietf-cellar-tags-00.md
mmark -xml2 -page draft-ietf-cellar-tags-00.md > draft-ietf-cellar-tags-00.xml
2018/07/25 19:23:27 mmark: syntax not supported: HRule
2018/07/25 19:23:27 mmark: syntax not supported: HRule
2018/07/25 19:23:27 mmark: syntax not supported: HRule
2018/07/25 19:23:27 mmark: syntax not supported: HRule
xml2rfc --html draft-ietf-cellar-tags-00.xml -o draft-ietf-cellar-tags-00.html
Parsing file draft-ietf-cellar-tags-00.xml
Created file draft-ietf-cellar-tags-00.html
xml2rfc draft-ietf-cellar-tags-00.xml -o draft-ietf-cellar-tags-00.txt
Parsing file draft-ietf-cellar-tags-00.xml
WARNING: so many <ttcol>s in <texttable> that some words need to be split near line 248
Created file draft-ietf-cellar-tags-00.txt

```




```

**Comment by dericed** [comment]
Thanks @kieranjol, it seems that the mmark/rfc2xml doesn't work with empty markdown table cells.

so this doesn't render properly in the rfc
```
|`0` |progressive ||
```

but this does
```
|`0` |progressive | |
```

The PR is updated so please re-review.

**Comment by robUx4** [comment]
Not pushed as it doesn't produce a correct output.

**Comment by robUx4** [comment]
I pushed a fix that fixes the issue for me.
Feel free to merge it.

**Pull request merged**
