### PR TITLE
implement enumeration lists

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by robUx4** [comment]
LGTM.

**Comment by retokromer** [comment]
LGTM

Personal note: The space before `/>` in empty tags was introduced, back in the late 1990s, for inaccurate parsers’ compatibility. I guess, _sensu stricto_, it’s not longer needed.

**Comment by dericed** [comment]
Changed `" />` to `"/>` as @retokromer pointed out. Will merge soon.

**Comment by retokromer** [comment]
LGTM

**Pull request merged**
