### PR TITLE
order ProRes flavours by decreasing quality

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by dericed** [comment]
Any rationale to prioritize sorting by quality rather than alphabet?

**Comment by retokromer** [comment]
Quality is relevant. (I'm working on an archival solution for ProRes in the post-QuickTime era.)

**Comment by retokromer** [comment]
BTW: the existing is not in alphabetical order, neither by FourCC nor by name…

**Comment by robUx4** [comment]
LGTM.

**Comment by retokromer** [comment]
Has 4444 XQ another FourCC than 4444? And, if so, which one?

**Comment by richardpl** [comment]
Yes, it is ap4x

**Comment by retokromer** [comment]
Thank you, @richardpl!

**Pull request merged**
