### PR TITLE
add block metadata structure

### PR DESCRIPTION
**Pull request by dericed**
addresses https://github.com/Matroska-Org/matroska-specification/issues/270

### CODE REVIEW

**Comment by dericed** [comment]
Updated to @mbunkus' suggestions, also removed some unneeded defaults.

**Comment by mbunkus** [comment]
What about renaming them? :)

**Comment by mbunkus** [comment]
And I meant giving the `Metadata` master a one-byte ID, too. It will be present for each metadata entry, just like `MetadataName` and one of `MetadataString`/`MetadataBinary`; hence it deserves a short ID, too.

**Comment by dericed** [comment]
thx @mbunkus, updated

**Comment by dericed** [comment]
@mbunkus, ok with BlockMetadata rather than FrameMetadata? Block* fits in context here better.

**Comment by dericed** [comment]
For #3 perhaps I can add a section to tagging.md that documents official MetadataName values. Taking the same approach as official/unofficial TagNames may make sense here.

**Comment by hubblec4** [comment]
I have read ever thing (email, issue, PR). It is very interesting and I understand a bit, because it is similar to the Tags.

I also think we need this Metadata system to preserve all info/data. +1

Where do I start best? I thought about that a little bit.

Mosu is right with the name and prefix: Only metadata would be too inaccurate.
Frame/BlockMetadata would be more accurate for the current project, because it could be, we need in the future
in another place in Matroska also metadata.

And I think of a job as well. For an edition. The edition is very often given a name nowadays.
Since there is no EditionName element you have to fall back on the Tags, which is a bit awkward when parsing.
Likewise it could happen that a user accidentally deletes / overwrites the Tags and already all edition names are gone.

I can well imagine that metadata in other places are very helpful.
At the Matroska meeting a woman told me that some audio data was lost while saving in Matroska.

Therefore, my consideration to make the Metadata element as a global element.

You would then only have a list for official/unofficial MetaNames like the TagNames.
Otherwise we would have to create a new list each time for a new Metadata system (for example AudioMetadata).

**Comment by hubblec4** [comment]
The MKVToolNix Track Statistics Tags is a very helpful feature, and it could be also stored in a Metadata Element for each track. I can imagine that would be better for a parser.

**Comment by mjbshaw** [comment]
Personally, I'd rather just use `BlockAdditions` for per-frame side metadata. After all, that's what it's for, isn't it?

**Comment by dericed** [comment]
I agree with @mjbshaw and think we can extend the use of BlockAdditions to cover other types of side frame data. Originally I thought this wasn't possible since the meaning of BlockAdditionId was handled by the codec mapping, with no reservation for the container to declare it's own ids. However from seeing how BlockAdditions has been used, I think it's safe to define BlockAdditionId=1 as in the context of the codec mapping (lossless part for WAVPACK4, alpha for VP8/VP9/others?). And then from 2 and up can be used for new mappings.

I think I prefer to close this without merge and move the effort to https://github.com/Matroska-Org/matroska-specification/pull/287.

**Comment by robUx4** [comment]
So we close the pull request ? I'm in favor of that.

**Comment by dericed** [comment]
Yes, I'll close. The scope of work has moved to https://github.com/Matroska-Org/matroska-specification/pull/287.

**Pull request closed without merging**
