### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by lu-zero**

### CODE REVIEW

**Comment by lu-zero** [comment]
We should maybe keep this this PR open while I keep reading the specification

**Comment by lu-zero** [comment]
I have @robUx4 next to me and hopefully I'll send some comments in the shape of patches  in a bit : )

**Comment by mbunkus** [comment]
Just let us know when we can start the review. And thanks!

**Comment by lu-zero** [comment]
So far those are all the typos I found, but as you noticed I moved my focus on the ebml specification =)

**Comment by dericed** [comment]
Will merge soon, as today is the doc freeze for IETF specs before IETF99.

**Pull request merged**
