### PR TITLE
Add rfc build process

### PR DESCRIPTION
**Pull request by dericed**
This is obviously a work in progress. Comments welcome, but don’t try to merge this yet. It does make a rfc output (sort of), but with many issues. A draft output is here https://gist.github.com/dericed/31e69f120d8acc8734b65909d7cf7f16. Tables aren’t working, many internal linking issues and lines that aren’t properly wrapping.

After the other PR’s are accepted, I review this and rebase.

### CODE REVIEW

**Comment by mbunkus** [comment]
I'll defer looking into this as it shouldn't be merged for tonight's deadline anyway if I understand you correctly.

**Comment by dericed** [comment]
I'm done with this PR, so please review. I left a note on this one https://github.com/Matroska-Org/matroska-specification/pull/31/commits/4ecd7aec00a8c6517a9ed3032711773cf3af931e as it needs a close review to make sure the semantics are consistent after the change, as it's only a formatting fix.

**Comment by dericed** [comment]
Also what's up with https://matroska.org/technical/specs/index.html#encryptedblock_structure, it is deprecated, should we include this section in the work of this repo?

**Comment by robUx4** [comment]
EncryptedBlock can go from the specs. We'll need to have a file that has the actual final specs and some of the things that were left behind to generate the code of libmatroska/libmatroska2 and possibly other pieces of code.

**Comment by robUx4** [comment]
LGTM

**Comment by mbunkus** [comment]
LGTM, too. As Steve's review has also found it to be fine I'll merge it.

**Pull request merged**
