### PR TITLE
change the luminance ranges to postive

### PR DESCRIPTION
**Pull request by robUx4**
We don't know if there won't be very small values or very large values someday.
Negative values there won't be.

Fixes issue #122

### CODE REVIEW

**Comment by dericed** [comment]
ping @frankgalligan

**Comment by dericed** [comment]
Don't you mean `>=`? After patch a zero value is not valid but before it is ok.

**Comment by robUx4** [comment]
Mh, I would think 0 is an invalid value. Yet again, it might be technically possible to film in a black box where there's absolutely no light by default. So I agree.

**Comment by dericed** [comment]
@FrankGalligan's original range for LuminanceMax included 0. An exactly black recording is certainly possible so I suggest `range="&gt;= 0x0p+0"` for both LuminanceMax and LuminanceMin.

**Comment by retokromer** [comment]
I discussed this at CERN last Friday. They don’t see a case study for `LuminanceMax = 0`. Yet I’m fine with either way allowing or not allowing it, as it don’t hurt.

**Comment by dericed** [comment]
I suggest that Matroska and webm keep compatibility where we can. With this change a webm would be valid with LuminanceMax=0 but when remuxed to Matroska would be invalid. See: https://www.webmproject.org/docs/container/.

**Comment by retokromer** [comment]
I fully agree on this!

**Comment by robUx4** [comment]
OK I updated to use `>=0` for both.

**Pull request merged**
