### PR TITLE
Clean Makefile

### PR DESCRIPTION
**Pull request by robUx4**
Using make -j2 will also build the .txt and .html outputs at the same time in parallel
Update the XSLT script will also trigger rebuilding the proper files

### CODE REVIEW

**Comment by dericed** [comment]
I tested this and it works well, produces the same output, but is far better written. However, when running `make` there is now no `draft-lhomme-cellar-matroska-01.xml` output and this is the file which is submitted to the ietf document tracker. Can you add `draft-lhomme-cellar-matroska-01.xml` back? Otherwise, LGTM.

**Comment by robUx4** [comment]
I put the regular expression change first, as otherwise none of these changes build in the end for me. It's nicer to always have something that builds first.

I also added a commit to keep the XML file.

**Comment by dericed** [comment]
LGTM

**Comment by retokromer** [comment]
LGTM

**Comment by robUx4** [comment]
Waiting on #97 before merging this.

**Pull request merged**
