### PR TITLE
add a local website generator to the Makefile

### LINKED ISSUE #146: Generate the github website from the Makefile
It may just be running some Jekyll commands as a Makefile target (like `website`).

That would help keep our Markdown and website generator happy together for longer.

### PR DESCRIPTION
**Pull request by robUx4**
Similar to the one generated automatically on Github:
http://matroska-org.github.io/matroska-specification/

Fixes #146

### CODE REVIEW

**Comment by ablwr** [comment]
Well, look at you go!

**Comment by robUx4** [comment]
That part is easy.
I wanted to remove the front-matter from each MarkDown file via the `_config.yml` but it doesn't seem possible.

**Comment by robUx4** [comment]
It's possible to have just ```---
---``` at the beginning of files. Which would generate clean IETF output. But the `layout: default` information is lost and it seems forcing it in `_config.yml` doesn't work :(

**Comment by ablwr** [comment]
I'll give it a try -- just now got my computer set up to have the `make` command build things properly instead of throwing errors at me! With regards to this specific change, 👍

**Comment by robUx4** [comment]
I created a branch with my failed attempt at removing the `layout: default` from each Markdown file.
https://github.com/Matroska-Org/matroska-specification/tree/layout-default

**Comment by ablwr** [comment]
I definitely remember struggling with this ~1 year ago because I didn't want the front-loaded YAML in there, either, but wasn't able to get a workaround (and didn't want to spend too much time on it). But Jekyll and I have both matured since then...

**Comment by ablwr** [comment]
This does seem to just be a limitation of Jekyll. I will update the _config.yml file with the default scope so the pages themselves are cleaner.

**Pull request merged**
