### PR TITLE
update elements as tables to sections

### PR DESCRIPTION
**Pull request by dericed**
this is done in the xsl which converts ebml_matroska.xml to markdown by
the Makefile to use in the rfc

### CODE REVIEW

**Comment by robUx4** [comment]
Not knowing much about XSLT I abstain from commenting.
@mbunkus looks good to you ?

**Comment by ablwr** [comment]
This upgrade makes a lot of smartly-written XSL upgrades. 👍

**Comment by mbunkus** [comment]
Well, the changes are so big that reviewing the diff doesn't make much sense. Unfortunately I cannot build the docs at the moment as `make` fails:

```
xml2rfc draft-lhomme-cellar-matroska-00.xml -o "draft-lhomme-cellar-matroska-00.txt"
Parsing file draft-lhomme-cellar-matroska-00.xml
Parsing file draft-lhomme-cellar-matroska-00.xml
WARNING: Parsing Error: Unescaped '<' not allowed in attributes values, line 6731, column 203
WARNING: Parsing Error: Unescaped '<' not allowed in attributes values, line 6731, column 203
ERROR: Unable to parse the XML document: draft-lhomme-cellar-matroska-00.xml
 draft-lhomme-cellar-matroska-00.xml: Line 6731: Unescaped '<' not allowed in attributes values
 draft-lhomme-cellar-matroska-00.xml: Line 6731: attributes construct error
 draft-lhomme-cellar-matroska-00.xml: Line 6731: Couldn't find end of Start Tag section
 draft-lhomme-cellar-matroska-00.xml: Line 6731: Unescaped '<' not allowed in attributes values
 draft-lhomme-cellar-matroska-00.xml: Line 6731: attributes construct error
 draft-lhomme-cellar-matroska-00.xml: Line 6731: Couldn't find end of Start Tag section line 6731
```

and other similar issues.

**Comment by dericed** [comment]
Right. The PR to update the Schema format has broken this. I can fix later.

**Comment by dericed** [comment]
This PR had to be rewritten since there had been so many changes to the `EBML Schema`. I updated the PR. Here's an example of the [old format of MKV Elements in the RFC](https://gist.github.com/dericed/1ef882f02bfce59de5e0ac1bada3e2a2) (though much in this is broken from the schema update) and here's an example of the [new format](https://gist.github.com/dericed/1ff91745e8fd0d0f60afeb9d26b940f2). The XSL is also much simpler and just replicates the new EBML Schema attribute structure in a `key: value` list.

**Comment by robUx4** [comment]
*MUCH* better looking

**Comment by dericed** [comment]
In that case, @ablwr, could you re-review the updated patch.

**Comment by ablwr** [comment]
LGTM.

**Pull request merged**
