### PR TITLE
add the explicit parent value to all elements

### PR DESCRIPTION
**Pull request by robUx4**
according to https://github.com/Matroska-Org/ebml-specification/pull/83

So noone has to do this boring task later.

### CODE REVIEW

**Comment by robUx4** [comment]
At some point we may flatten the XML. The wrapping information is a duplicate information of the `parent` value. The `level` value is probably not needed anymore.

Also the cppname should probably be an item like the `description`. So the `element` only has attributes defined in the EBML schema/RFC.

**Comment by dericed** [comment]
The `<element>` nodes are now all at the same level. Also via this [xsl](https://gist.github.com/dericed/ddb0eaa6bb4f0983825e715d45ff6141) I converted the `parent` attribute to the new `path` attribute and dropped the redundant `level` attribute.

**Comment by mbunkus** [comment]
I'm fine with merging this. Objections?

**Comment by robUx4** [comment]
LGTM, I'll will try to recreate the table of elements on my side to confirm there's no inconsistencies. But that can be fixed later. We should not block this.

**Pull request merged**
