### PR TITLE
Menu and streaming nesting

### PR DESCRIPTION
**Pull request by ablwr**
Similar to #163 but for Menu and Streaming sections, although there seems to be a bug present in master while building the Menu section, causing the final paragraph to be considered one of the headers. I've messed around with trying to sort this out, but no luck yet. Anyway, shouldn't block this small structural update.

### CODE REVIEW

**Comment by ablwr** [comment]
What's the justification in squashing? Each commit covers each section!

**Comment by mbunkus** [comment]
They're both trivial and do the same thing, just for different sections. In my opinion "next menu and streaming items" would suffice as a description.

I'm just not a friend of having too many commits. It can make working with the history more difficult than necessary. Yes, one commit for one logical/semantic change, and yes, this is debatable in this case.

I'd be fine with keeping both commits, though. I'm not that dogmatic.

**Comment by ablwr** [comment]
I squashed! And I will return to tidy up both of these sections.

**Comment by mbunkus** [comment]
I didn't mean to imply that you should squash it. It was intended as a reminder for whoever merges it to use github's "squash and merge" functionality. But thanks anyway 😄

**Pull request merged**
