### PR TITLE
all US English

### PR DESCRIPTION
**Pull request by retokromer**
- otherwise change `organizational`

### CODE REVIEW

**Comment by dericed** [comment]
There's some guidance in https://tools.ietf.org/html/rfc7322#section-3.1 in support of consistency. Perhaps worthwhile to query the working group for consensus before shifting the documentation to Americanized English as the majority of contributors and writings have been from non-American authors.

**Comment by retokromer** [comment]
I personally prefer UK English, but in this case `organizational` is wrong.

**Comment by JeromeMartinez** [comment]
The majority of contributors are also non-English ;-).
As section 3.1 slightly prioritize American English, I am in favor of American English.

**Comment by retokromer** [comment]
That‘s exactly the reason why I changed to US English, despite the fact that I personally would prefer UK English.

**Comment by robUx4** [comment]
Probably better to go with the newer version of English, so the US one.
There are many cases of the work `Initialisation` in the codec specs but in general the intent was to use US English.

**Comment by retokromer** [comment]
OK, i’ll make a PR later on this.

**Pull request merged**
