### PR TITLE
Mmark clean

### PR DESCRIPTION
**Pull request by robUx4**
On top of the Makefile cleaning branch

The `layout:` lines are not cleaned properly for me and then mmark produces junk output.

### CODE REVIEW

**Comment by retokromer** [comment]
On Slackware 14.1 as well: https://github.com/Matroska-Org/matroska-specification/pull/97/commits/b230559e4d37765ce883a564e0ea0e006f8c71c6

LGTM

**Comment by mbunkus** [comment]
Hmm, this PR includes the changes from #95, doesn't it? Makes it a bit harder to review what changed in this particular PR only.

**Comment by robUx4** [comment]
Yes, that's only the last commit. It depends on the other commits being merged. If they're not I will make a different version. But it won't merge/rebase cleanly into branch #95.

**Comment by robUx4** [comment]
Don't we want to cover just this problematic section that is (oddly) generated ?

**Comment by dericed** [comment]
LGTM

**Comment by mbunkus** [comment]
Like I said: `grep -v '^---\|^layout:\|^---\b'` is equivalent to `grep -v '^---\|^layout:'` (as `^---` always matches where `^---\b` matches). As I prefer clarity, I'd ask you to change this to `grep -v '^---\|^layout:'`.

**Comment by robUx4** [comment]
I updated the commit to match this.

**Pull request merged**
