### PR TITLE
removes line of advice for player implementation

### PR DESCRIPTION
**Pull request by ablwr**
This is good advice, but I don't think it fits in the spec. If it does fit in the spec, I don't think it fits here, not in a category, at the beginning of the notes section (which immediately follows the schema structure details).

### CODE REVIEW

**Comment by retokromer** [comment]
Will there be a document on player implementation?

**Comment by ablwr** [comment]
There aren't plans to make one as part of standardization. There could be an independent guide... but the spec itself should be clear enough that it isn't necessary.

**Comment by retokromer** [comment]
While working on FLAC people showed up and give us useful hints, in order to avoid the mistakes they made. I was thinking about something like that, in addition to the specs.

**Comment by ablwr** [comment]
@mbunkus is the expert!

**Comment by retokromer** [comment]
Therefore he is an excellent candidate for writing such a guide ;-)

**Comment by mbunkus** [comment]
Not really. I've never written Matroska for a media player or a media player in general myself. I'm much more knowledgeable regarding creating Matroska files.

The only real advice I have is… don't forget about default values.

**Comment by JeromeMartinez** [comment]
+1 for removing this part from spec, not the right place.

I see the same kind of sentence on https://matroska.org/technical/specs/notes.html (the first paragraph) , isn't it what is expected?

**Comment by mbunkus** [comment]
The thing with expectations is that everyone has different ones. Stating that there is a test suite and that people should use it is a good thing. However, such advice has no place in an RFC.

**Comment by retokromer** [comment]
It has definitely nothing to do in the specifications. I guess we all agree on this.

However I would personally like to see it as an additional document. Not just to put it into the rubbish bin. That‘s my only point.

**Comment by ablwr** [comment]
Perhaps you want to bring this up on the CELLAR list instead of this not-well-viewed pull request?

**Comment by retokromer** [comment]
@ablwr Done.

**Pull request merged**
