### PR TITLE
fix to Default Edition logic

### PR DESCRIPTION
**Pull request by dericed**
fixes the error that @hubblec4 found in https://github.com/Matroska-Org/matroska-specification/pull/190#issuecomment-331874813

### CODE REVIEW

**Comment by hubblec4** [comment]
Now it is ok.

**Comment by dericed** [comment]
@hubblec4 I am still curious of:

> When all `EditionFlagDefault Flags` are set to `false`, then the first `Edition` is the `Default Edition`.

So:
```
edition 1
 - default false
 - hidden true
edition 2
 - default false
 - hidden false
```

The Default Edition is `1`, right? Since all Editions have default set to false.

**Comment by hubblec4** [comment]
Yes you are right. The description is not perfect.

..., then the first `Edition` with `EditionFlagHidden Flag` set to `false` is the `Default Edition`.

"... is the Default Edition" is also not really right, better is: 

... is the `Edition` which have to use. 

A Default Edition Flag is not set, so we can't call it Default Edition.

**Comment by hubblec4** [comment]
Maybe it make sense to define the term  `Default Edition`:

The `Default Edition` is the `Edition` which MUST played by the `Matroska Player`.

**Comment by hubblec4** [comment]
When all `EditionFlagDefault Flags` are set to `false`, then the first `Edition` with the `EditionFlagHidden Flag` is set to `false` MUST played by the `Matroska Player`.

**Pull request merged**
