### PR TITLE
moves track operation and overlay track under track flags section

### PR DESCRIPTION
**Pull request by ablwr**

### CODE REVIEW

**Comment by mbunkus** [comment]
Not merging right away in order to give others the opportunity to comment. If no one objects within a week, just merge it.

**Comment by mbunkus** [comment]
This cannot be merged cleanly at the moment. Can you please rebase it manually, @ablwr? Then just merge & push without a new round trip through this PR.

**Comment by ablwr** [comment]
No? I did rebase; the above "fix conflict line" commit is a clean merge

**Comment by dericed** [comment]
seems mergable to me

**Comment by mbunkus** [comment]
Ah right, "squash & merge" works, but "rebase & merge" doesn't. As squashing is what I would want to do anyway, this is fine.

**Pull request merged**
